apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginxsvc
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 32015
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: nginx
  type: LoadBalancer
